# Generated by Django 4.2.2 on 2023-09-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdata_is_admin_alter_userdata_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
