# Generated by Django 4.2.2 on 2023-09-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_ingredients_alter_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(max_length=1500),
        ),
    ]
